{% set version = "6.14.1" %}

package:
  name: flex-swagger
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/f/flex/flex-{{ version }}.tar.gz
  sha256: 292ed6a37f1ac0a10ad8669f5ceb82e8ba3106c16c54090820927bac8b0b29eb

build:
  noarch: python
  number: 1
  entry_points:
    - swagger-flex=flex.cli:main
  script: {{ PYTHON }} -m pip install -vv --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - click >=3.3
    - jsonpointer >=1.7
    - python >={{ python_min }}
    - pyyaml >=3.11
    - requests >=2.4.3
    - rfc3987 >=1.3.4
    - six >=1.7.3
    - strict-rfc3339 >=0.7
    - validate_email >=1.2

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - flex
    - flex.compat
    - flex.loading
    - flex.loading.common
    - flex.loading.common.schema
    - flex.loading.common.single_header
    - flex.loading.common.single_parameter
    - flex.loading.definitions
    - flex.loading.definitions.parameters
    - flex.loading.definitions.responses
    - flex.loading.definitions.responses.single
    - flex.loading.definitions.responses.single.headers
    - flex.loading.definitions.schema
    - flex.loading.schema
    - flex.loading.schema.paths
    - flex.loading.schema.paths.path_item
    - flex.loading.schema.paths.path_item.operation
    - flex.loading.schema.paths.path_item.operation.parameters
    - flex.loading.schema.paths.path_item.operation.responses
    - flex.loading.schema.paths.path_item.operation.responses.single
    - flex.loading.schema.paths.path_item.operation.responses.single.headers
    - flex.loading.schema.paths.path_item.operation.responses.single.schema
    - flex.loading.schema.paths.path_item.parameters
    - flex.validation
  commands:
    - swagger-flex --help
    - pip check

about:
  home: https://github.com/pipermerriam/flex
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Swagger Schema validation.
  description: Validation tooling for Swagger 2.0 specifications.
  doc_url: https://flex-swagger.readthedocs.org
  dev_url: https://github.com/pipermerriam/flex

extra:
  recipe-maintainers:
    - RohitK89
    - mariusvniekerk
    - bollwyvl
