travis:
  secure:
    BINSTAR_TOKEN: kg4Np6E0ivHPWCHq5Feid2Hb7keBCMKkqDqOzoTmtnrz8kn/rErwjljTBhEe3ZPad4qWB7mA0+d1MPQij86K9fOvqyTdECV32AzLX2e5l35znzgUYmoTu5gRkxSlxF9CAfbB28Lx0tDepUJXP0mhnQWWu2Y1+LSZhhdY3tRERHaad1KkooyJj7uWEZGK5vFphzSqp/jjTVgLDLTYJK3bq1u1Qj9+m37kz8Xgf/aFv8NOGN1g7jqRi/l09nIXMgZhrE6CKzBEYwPrhLYwcnSym6Wrxky2STrNYp1IVn4V9NkvwF998FpUMWt2T9A0D6LMhEjThF/17WRkUlfrtfYEITjaYVs+FtWLRmdjyiKdZfhKH0F8MymIeoBK41as9+ZxpKMvJcIjVzx/QJVy7xajf4Ua8v82eEslsnlXMa/wJ2Usoj8cwdgvm4GvTkWFiUCoo7roeyMZRyeVYOjGQeDLmmmfZ1fAlUPYUhlqM/FTrr9fvwjjVa+nPn/PyHnGwOG9EeZ1an4M7466imj027Yn3n4CusQo7rAWMTLzUMqNW29+l/EowGXEWY/gA+vnuvpS+FOXI5uTZWBPtxobtb8bkJfzawLU6EkoRPrpmLvWTzijTu4xZPBw4oMneuJjcg+C90RNhRe1SO8PUca+J35dfi+izk0qsMUi3PP0xfRE08I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
